### ISSUE TITLE
crosscap.permitting still not finding the right argument in requests

### ISSUE THREAD

**Issue by corydodt** [corydodt/Crosscap#14]

**Comment by corydodt** [comment]
```
2019-06-05 10:59:40-0700 [_GenericHTTPChannelProtocol,0,127.0.0.1] Unhandled Error
	Traceback (most recent call last):
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/twisted/web/server.py", line 241, in render
	    body = resrc.render(self)
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/klein/resource.py", line 111, in render
	    d = defer.maybeDeferred(_execute)
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/klein/resource.py", line 105, in _execute
	    **kwargs)
	--- <exception caught here> ---
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/klein/app.py", line 87, in execute_endpoint
	    return endpoint_f(self._instance, *args, **kwargs)
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/klein/app.py", line 172, in _f
	    return _call(instance, f, request, *a, **kw)
	  File "/Users/corydodt/.virtualenvs/aorta/lib/python2.7/site-packages/klein/app.py", line 29, in _call
	    return f(instance, *args, **kwargs)
	  File "/Users/corydodt/src/Crosscap/crosscap/permitting/core.py", line 77, in wrapper
	    authuser = ICurrentUser(handler)
	exceptions.TypeError: ('Could not adapt', <ganglion.web.epi.EpiAPI object at 0x10f833350>, <InterfaceClass crosscap.interface.ICurrentUser>)
```
